
export const dark = '#6E737B'
export const darkAccent = '#494f52'
export const darkLowlight = '#151718'
export const light = '#777'
export const lightAccent = '#9ea1ad'
export const lightLowlight = '#c5c5c5'
export const main = '#FFF'
export const errorText = '#ff6459'
export const errorBackground = '#EC9590'
